### ISSUE TITLE
Direction

### ISSUE THREAD

**Issue by volkov** [volkov/znavi#6]
```
2021-01-02 10:29:16,856 [  45724]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.trace(ShowUsagesActionClone.java:578)
2021-01-02 10:29:16,857 [  45725]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.showElementUsages(ShowUsagesActionClone.java:359)
2021-01-02 10:29:16,857 [  45725]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.startFindUsages(ShowUsagesActionClone.java:276)
2021-01-02 10:29:16,857 [  45725]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone$1.handlePsi(ShowUsagesActionClone.java:225)
2021-01-02 10:29:16,857 [  45725]   INFO -                         STDERR -     at com.intellij.find.actions.PsiTargetVariant.handle(resolver.kt:108)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.find.actions.ResolverKt.findShowUsages(resolver.kt:50)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.showUsages(ShowUsagesActionClone.java:202)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.showSymbolUsages(ShowUsagesActionClone.java:192)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.actionPerformed(ShowUsagesActionClone.java:184)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.ide.actions.GotoActionAction.lambda$performAction$2(GotoActionAction.java:104)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
2021-01-02 10:29:16,858 [  45726]   INFO -                         STDERR -     at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
2021-01-02 10:29:16,859 [  45727]   INFO -                         STDERR -     at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
2021-01-02 10:29:16,859 [  45727]   INFO -                         STDERR -     at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
2021-01-02 10:29:16,859 [  45727]   INFO -                         STDERR -     at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
2021-01-02 10:29:16,859 [  45727]   INFO -                         STDERR -     at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
2021-01-02 10:29:16,859 [  45727]   INFO -                         STDERR -     at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
2021-01-02 10:29:16,859 [  45727]   INFO -                         STDERR -     at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
2021-01-02 10:29:16,859 [  45727]   INFO -                         STDERR -     at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
2021-01-02 10:29:16,859 [  45727]   INFO -                         STDERR -     at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
```

**Comment by volkov** [comment]
```
2021-01-02 10:52:39,771 [ 648050]   INFO -                         STDERR - java.lang.RuntimeException
2021-01-02 10:52:39,771 [ 648050]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.trace(ShowUsagesActionClone.java:578)
2021-01-02 10:52:39,771 [ 648050]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.showElementUsages(ShowUsagesActionClone.java:359)
2021-01-02 10:52:39,771 [ 648050]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.showUsagesInMaximalScope(ShowUsagesActionClone.java:1176)
2021-01-02 10:52:39,771 [ 648050]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.lambda$showUsagesInMaximalScopeRunnable$26(ShowUsagesActionClone.java:1171)
2021-01-02 10:52:39,771 [ 648050]   INFO -                         STDERR -     at com.intellij.find.actions.ShowUsagesActionClone.actionPerformed(ShowUsagesActionClone.java:176)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:615)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:675)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:674)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:522)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:476)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:892)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:837)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
2021-01-02 10:52:39,772 [ 648051]   INFO -                         STDERR -     at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
2021-01-02 10:52:39,773 [ 648052]   INFO -                         STDERR -     at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
2021-01-02 10:52:39,773 [ 648052]   INFO -                         STDERR -     at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
2021-01-02 10:52:39,773 [ 648052]   INFO -                         STDERR -     at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
2021-01-02 10:52:39,773 [ 648052]   INFO -                         STDERR -     at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2021-01-02 10:52:39,773 [ 648052]   INFO -                         STDERR -     at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
